[pytest]
filterwarnings = 
    ignore:`torch\.jit\.script` is deprecated\. Please switch to `torch\.compile` or `torch\.export`\.:DeprecationWarning:torch\.jit\._script
    ignore:add more warning filters here as needed
